### ISSUE TITLE
Stabilize code and release new version in accordance with paper release and the end of the course

### ISSUE THREAD

**Issue by msricher** [theochem/PyCI#60]
# Todo

* [ ]  Clean up the contributed code from the course. I've just been doing `black -l 100` on my own Python files so far, but I will add some proper pre-commit hooks to take care of this once the course is done.
* [ ] Improve C++ code comments.
* [ ] Bump version number to 0.7.0.
* [ ] Include in the README and website a section like the following with a bibtex entry once the paper is published:
        Citing PyCI:
        -----------------
        Please cite PyCI in accordance with the following if you use it for published research:
    ```bibtex
    @article{2024pyci
    ...
    }
    ```

I would also appreciate others' thoughts on what should be done during this time.
